# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'projekt_22_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WtyczkaDialogBase(object):
    def setupUi(self, WtyczkaDialogBase):
        WtyczkaDialogBase.setObjectName("WtyczkaDialogBase")
        WtyczkaDialogBase.resize(498, 470)
        self.button_box = QtWidgets.QDialogButtonBox(WtyczkaDialogBase)
        self.button_box.setGeometry(QtCore.QRect(90, 410, 251, 51))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.listWidget = QtWidgets.QListWidget(WtyczkaDialogBase)
        self.listWidget.setGeometry(QtCore.QRect(110, 70, 271, 261))
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget.setObjectName("listWidget")
        self.label = QtWidgets.QLabel(WtyczkaDialogBase)
        self.label.setGeometry(QtCore.QRect(190, 20, 201, 41))
        self.label.setObjectName("label")
        self.radioButton = QtWidgets.QRadioButton(WtyczkaDialogBase)
        self.radioButton.setGeometry(QtCore.QRect(70, 370, 95, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(WtyczkaDialogBase)
        self.radioButton_2.setGeometry(QtCore.QRect(330, 370, 95, 20))
        self.radioButton_2.setObjectName("radioButton_2")

        self.retranslateUi(WtyczkaDialogBase)
        self.button_box.accepted.connect(WtyczkaDialogBase.accept) # type: ignore
        self.button_box.rejected.connect(WtyczkaDialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(WtyczkaDialogBase)

    def retranslateUi(self, WtyczkaDialogBase):
        _translate = QtCore.QCoreApplication.translate
        WtyczkaDialogBase.setWindowTitle(_translate("WtyczkaDialogBase", "Wysokość i Pole"))
        self.label.setText(_translate("WtyczkaDialogBase", "Wybierz punkty:"))
        self.radioButton.setText(_translate("WtyczkaDialogBase", "Wysokość"))
        self.radioButton_2.setText(_translate("WtyczkaDialogBase", "Pole"))
